name: Deploy Release

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: init stuff
        uses: ./.github/actions/init

      - name: build
        run: npm run build

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
