name: Deploy to npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
      distTag:
        description: 'Used as npm publish --tag'
        default: 'latest'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: init stuff
        uses: ./.github/actions/init

      - name: build
        run: npm run build

      - name: set version
        run: npm version ${{ github.event.inputs.version }}

      - name: publish
        run: npm publish --tag ${{ github.event.inputs.distTag }}
        env:
          NPM_CONFIG_PROVENANCE: true

      - name: push
        run: git push origin --tags ${{ github.ref_name }}
