name: Deploy
on:
  push:
    tags:
      - 'v*'
      - '!v*-*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch deps
      shell: bash
      run: yarn
    - name: Build
      shell: bash
      run: yarn build
    - name: Build Docs
      shell: bash
      run: yarn docs
    - name: Upload Builds
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
    - name: Upload Types
      uses: actions/upload-artifact@v1
      with:
        name: types
        path: types
    - name: Upload Docs
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Download Builds
      uses: actions/download-artifact@v1
      with:
        name: dist
        path: dist
    - name: Download Builds
      uses: actions/download-artifact@v1
      with:
        name: types
        path: types
    - name: Download Builds
      uses: actions/download-artifact@v1
      with:
        name: docs
        path: docs
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Download Builds
      uses: actions/download-artifact@v1
      with:
        name: dist
        path: pages/dist
    - name: Download Builds
      uses: actions/download-artifact@v1
      with:
        name: types
        path: pages/types
    - name: Download Builds
      uses: actions/download-artifact@v1
      with:
        name: example
        path: pages/example
    - name: Deploy gh-pages
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pages
