name: Inspect

on: push

defaults:
  run:
    shell: bash

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Fetch Deps
      run: yarn install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Lint
      run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Build
      run: yarn build
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          dist/
          ts*/
          types/

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Download Builds
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Build Docs
      run: yarn docs
    - name: Upload Docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: |
          docs/

  gh-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    needs:
    - build
    - docs
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Download Builds
      uses: actions/download-artifact@v2
      with:
        name: build
        path: public
    - name: Download Docs
      uses: actions/download-artifact@v2
      with:
        name: docs
        path: public/docs
    - name: Copy Example
      run: |
        cp -r example public/example
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
